required_plugins = %w(vagrant-docker-compose vagrant-docker-login)

plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

machines = {
  "master" => {"memory" => "1024", "cpu" => "1", "ip" => "100", "image" => "ubuntu/focal64", "port" => "3000"},
  "vm1" => {"memory" => "1024", "cpu" => "1", "ip" => "101", "image" => "ubuntu/focal64",  "port" => "3001"},
  "vm2" => {"memory" => "1024", "cpu" => "1", "ip" => "102", "image" => "ubuntu/focal64",  "port" => "3002"}
}

Vagrant.configure("2") do |config|
  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}"
      machine.vm.network "private_network", ip: "10.10.10.#{conf["ip"]}"
      machine.vm.network "forwarded_port", guest: "80", host: "#{conf["port"]}", auto_correct: true
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        # vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        # vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

      end
      config.vm.provision :shell, inline: "export DOCKER_CLIENT_TIMEOUT=120", run: "always"
      config.vm.provision :shell, inline: "export COMPOSE_HTTP_TIMEOUT=120", run: "always"

      config.vm.synced_folder ".", "/vagrant"
      config.vm.provision :docker

      if "#{name}" == "master"
        machine.vm.provision "shell", path: "master.sh"
      else
        machine.vm.provision "shell", path: "worker.sh"
      end

      if "#{name}" == "vm1"
        machine.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", run: "always"
        machine.vm.provision "shell", path: "pokedex.sh"
      end

    end
  end
end